server:
  port: 8090

# JWT Secret Key
jwt:
  secret: BYDBCQAgCEVn+1N0Nol6ICbR+gfRfvgxcqypqsDtc7MB

spring:
  application:
    name: api-gateway

  cloud:
    # Disabling Config Server check as we did in the properties file
    config:
      enabled: false
    gateway:
      # CORS POLICY
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # Registration Service Route
        - id: Iam-FarmerRegistration-Service
          uri: lb://IAM-FARMERREGISTRATION-SERVICE
          predicates:
            - Path=/users/**, /documents/**, /farmers/**, /api/logs/**

        # Report Service
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/report/**

        # Report Service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notification/**

        #Crop Listing and Order
        - id: croplisting-service
          uri: lb://CROPLISTING-SERVICE
          predicates:
            - Path=/market/**

        #transactions and payments
        - id: transaction-payment
          uri: lb://TRANSACTION-PAYMENT
          predicates:
            - Path=/transactions/** , /payments/**
          filters:
            # This is essential so the Transaction service sees "/transactions/initiate"
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # Subsidy Service
        - id: subsidy-service
          uri: lb://SUBSIDY-SERVICE
          predicates:
            - Path=/subsidy-programs/**, /disbursements/**

        # --- Audit Service ---
        - id: AUDIT-COMPLIANCE-SERVICE
          uri: lb://AUDIT-COMPLIANCE-SERVICE
          predicates:
            - Path=/api/audits/**, /api/compliances/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # Opens the endpoints to be accessible via HTTP
        include: "*"
  endpoint:
    health:
      # Shows details like disk space and db status
      show-details: always
  info:
    env:
      # Required in Spring Boot 3+ to see data in /actuator/info
      enabled: true
