import { AuditStatus, AuditScope ,ComplianceResult,ComplianceType } from "./enum.model";

export interface CropListingDTO {
  listingId?: number;
  farmerId: number;
  cropType: string;
  quantity: number;
  price: number;
  location: string;
  status?: string;
  documentUrl?: string;
  farmerNumber?: string;
}

export interface OrderDTO {
  orderId?: number;
  listingId: number;
  traderId: number;
  quantity: number;
  orderDate: string;
  orderStatus?: string;
}

export interface ReportDTO {
  scope: string;
  metrics: string;
}

export interface Report {
  reportId: number;
  scope: string;
  metrics: string;
  generatedDate: string;
}

export interface NotificationDTO {
  userId?: number;
  role?: string;
  subject: string;
  message: string;
  category: string;
  status?: string;
}

export interface Notification {
  notificationID: number;
  userId?: number;
  role?: string;
  subject: string;
  message: string;
  category: string;
  status: string;
  createdDate: string;
}

export interface AuditLogDto {
  id: number;
  action: string;
  details: string;
  performedBy: string;
  role: string;
  timestamp: string;
}

export interface AuditDTO {
    auditId?: number;      // Optional because it's generated by the database
    officerId: number;     // ID of the officer conducting the audit
    scope: AuditScope;     // Uses the enum above
    findings: string;      // Summary of audit observations
    date: string;          // Formatted as yyyy-MM-dd
    status: AuditStatus;   // Uses the enum above
}
export interface ComplianceDTO {
    complianceId?: number;
    auditId: number;
    entityId: number;
    type: ComplianceType;
    result: ComplianceResult;
    date: string;
    notes: string;
}

export interface DisbursementDTO {
    disbursementId?: number;
    farmerId: number;
    programId: number;
    disbursementAmount: number;
}

export interface Disbursement {
    disbursementID: number;
    farmerId: number;
    programId: number;
    disbursementAmount: number;
    subsidyProgram?: {
        programID: number;
        title: string;
        description: string;
        startDate: string;
        endDate: string;
        allottedBudget: number;
        consumedBudget: number;
        subsidyStatus: 'PENDING' | 'VALIDATED' | 'REJECTED';
    };
    status?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'REJECTED';
    disbursementDate?: string;
}